spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: haril
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true